export enum JobType {
  AccountsIngest = "AccountsIngest",
  AccountsCountIngest = "AccountsCountIngest",
  AccountsBalanceIngest = "AccountsBalanceIngest",
  AccountsDelegationIngest = "AccountsDelegationIngest",
  AccountsDelegationLegacyActiveIngest = "AccountsDelegationLegacyActiveIngest",
  AccountsTotalBalanceWithStakeIngest = "AccountsTotalBalanceWithStakeIngest",
  AccountsTotalStakeIngest = "AccountsTotalStakeIngest",
  EconomicsIngest = "EconomicsIngest",
  ExchangesIngest = "ExchangesIngest",
  ExchangesDetailedIngest = "ExchangesDetailedIngest",
  GithubIngest = "GithubIngest",
  GithubActivityIngest = "GithubActivityIngest",
  GithubCommitsIngest = "GithubCommitsIngest",
  GithubContributorsIngest = "GithubContributorsIngest",
  GoogleIngest = "GoogleIngest",
  MaiarDexIngest = "MaiarDexIngest",
  TrendsIngest = "TrendsIngest",
  QuotesIngest = "QuotesIngest",
  StakingIngest = "StakingIngest",
  StakingNewIngest = "StakingNewIngest",
  StakingDetailedIngest = "StakingDetailedIngest",
  TransactionsIngest = "TransactionsIngest",
  TransactionsDetailedIngest = "TransactionsDetailedIngest",
  TwitterIngest = "TwitterIngest",
  PricesIngest = "PricesIngest",
}
